import type { Guest } from "./simulation";
const first = [
  "Emilia",
  "Noah",
  "Mila",
  "Leon",
  "Lina",
  "Paul",
  "Emma",
  "Elias",
  "Mia",
  "Finn",
  "Leni",
  "Ben",
  "Ida",
  "Luis",
  "Hanna",
  "Theo",
  "Lia",
  "Luca",
  "Clara",
  "Henry",
  "Sofia",
  "Oskar",
  "Lea",
  "Felix",
  "Marie",
  "Jonas",
  "Amira",
  "Sami",
  "Yuna",
  "Kian",
  "Ada",
  "Nico",
  "Nora",
  "Anton",
  "Elif",
  "Mika",
  "Juna",
  "David",
  "Zoe",
  "Alex",
];
const last = [
  "Weber",
  "Wagner",
  "Becker",
  "Hoffmann",
  "Schäfer",
  "Koch",
  "Bauer",
  "Richter",
  "Klein",
  "Wolf",
  "Schröder",
  "Neumann",
  "Schwarz",
  "Braun",
  "Zimmermann",
  "Krüger",
  "Hartmann",
  "Lange",
  "Schmitt",
  "Werner",
  "Krause",
  "Lehmann",
  "Schmid",
  "Schulz",
  "Keller",
  "Berger",
  "Roth",
  "Fuchs",
  "Nguyen",
  "Yilmaz",
  "Kaya",
  "Winter",
  "Sommer",
  "Vogel",
  "Hahn",
  "Lorenz",
  "Schuster",
  "Brandt",
  "Maier",
  "Frank",
];
export function guestName(id: number) {
  let n = Math.imul(id ^ 0x61c88647, 0x45d9f3b);
  n = Math.imul(n ^ (n >>> 16), 0x45d9f3b);
  n = (n ^ (n >>> 16)) >>> 0;
  return `${first[n % first.length]} ${last[Math.floor(n / first.length) % last.length]}`;
}
export function guestAppearance(g?: Pick<Guest, "id" | "skin">) {
  const id = g?.id ?? 0,
    skin = g?.skin ?? 0;
  return {
    skin: ["#e9b889", "#d49b6a", "#925f43"][skin],
    shirt: skin === 1 ? "#269baa" : "#e76849",
    hair: ["#493222", "#744722", "#bd8849", "#292622"][id % 4],
    pants: ["#304968", "#465666", "#596247"][id % 3],
    shoes: id % 2 ? "#f0eadb" : "#303637",
  };
}
